In [179]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Pre Processing
---

In [180]:
btc_usdt = pd.read_csv('order_book_data/BTCUSDT_1s.csv')
wbtc_usdt = pd.read_csv('order_book_data/WBTCUSDT_1s.csv')
eth_usdt = pd.read_csv('order_book_data/ETHUSDT_1s.csv')
wbeth_usdt = pd.read_csv('order_book_data/WBETHUSDT_1s.csv')

In [181]:
#Order by local_timestamp
btc_usdt = btc_usdt.sort_values(by='local_timestamp')
wbtc_usdt = wbtc_usdt.sort_values(by='local_timestamp')
eth_usdt = eth_usdt.sort_values(by='local_timestamp')
wbeth_usdt = wbeth_usdt.sort_values(by='local_timestamp')


#Drop Unamed column
btc_usdt = btc_usdt.drop(columns=['Unnamed: 0'])
wbtc_usdt = wbtc_usdt.drop(columns=['Unnamed: 0'])
eth_usdt = eth_usdt.drop(columns=['Unnamed: 0'])
wbeth_usdt = wbeth_usdt.drop(columns=['Unnamed: 0'])

#Convert local_timestamp to datetime
btc_usdt['local_timestamp'] = pd.to_datetime(btc_usdt['local_timestamp'])
wbtc_usdt['local_timestamp'] = pd.to_datetime(wbtc_usdt['local_timestamp'])
eth_usdt['local_timestamp'] = pd.to_datetime(eth_usdt['local_timestamp'])
wbeth_usdt['local_timestamp'] = pd.to_datetime(wbeth_usdt['local_timestamp'])

#Set local_timestamp as index
btc_usdt = btc_usdt.set_index('local_timestamp')
wbtc_usdt = wbtc_usdt.set_index('local_timestamp')
eth_usdt = eth_usdt.set_index('local_timestamp')
wbeth_usdt = wbeth_usdt.set_index('local_timestamp')

In [182]:
btc_usdt

,symbol,asks[0].price,asks[0].amount,bids[0].price,bids[0].amount
local_timestamp,,,,,
2024-06-01 00:00:00,BTCUSDT,67547.76,0.34897,67547.75,3.27941
2024-06-01 00:00:01,BTCUSDT,67547.76,0.85531,67547.75,6.69047
2024-06-01 00:00:02,BTCUSDT,67547.76,0.84523,67547.75,6.80568
2024-06-01 00:00:03,BTCUSDT,67547.76,0.79983,67547.75,6.80568
2024-06-01 00:00:04,BTCUSDT,67547.76,0.42881,67547.75,7.11088
...,...,...,...,...,...
2024-12-31 23:59:55,BTCUSDT,93576.01,3.96097,93576.00,0.56225
2024-12-31 23:59:56,BTCUSDT,93576.01,3.96097,93576.00,0.56245
2024-12-31 23:59:57,BTCUSDT,93576.01,4.17420,93576.00,0.35615
2024-12-31 23:59:58,BTCUSDT,93576.01,4.31092,93576.00,0.35545
2024-12-31 23:59:59,BTCUSDT,93576.01,3.52974,93576.00,0.61202

In [183]:
#Filter date range to 2024-06-01 to 2024-12-31 
btc_usdt = btc_usdt.loc['2024-06-01':'2024-12-31']
wbtc_usdt = wbtc_usdt.loc['2024-06-01':'2024-12-31']
eth_usdt = eth_usdt.loc['2024-06-01':'2024-12-31']
wbeth_usdt = wbeth_usdt.loc['2024-06-01':'2024-12-31']

In [184]:
eth_usdt

,symbol,asks[0].price,asks[0].amount,bids[0].price,bids[0].amount
local_timestamp,,,,,
2024-06-01 00:00:02,ETHUSDT,3762.70,5.9667,3762.69,52.6466
2024-06-01 00:00:03,ETHUSDT,3762.70,5.8263,3762.69,52.6677
2024-06-01 00:00:04,ETHUSDT,3762.70,5.8013,3762.69,56.9970
2024-06-01 00:00:05,ETHUSDT,3763.07,26.8783,3763.06,59.8217
2024-06-01 00:00:06,ETHUSDT,3763.33,5.7079,3763.32,40.4943
...,...,...,...,...,...
2024-12-31 23:59:55,ETHUSDT,3337.79,22.0972,3337.78,5.9750
2024-12-31 23:59:56,ETHUSDT,3337.79,21.7644,3337.78,5.9552
2024-12-31 23:59:57,ETHUSDT,3337.79,21.7707,3337.78,5.9545
2024-12-31 23:59:58,ETHUSDT,3337.79,26.0538,3337.78,2.9058
2024-12-31 23:59:59,ETHUSDT,3337.79,22.7346,3337.78,4.4490

In [185]:
wbeth_usdt

,symbol,asks[0].price,asks[0].amount,bids[0].price,bids[0].amount
local_timestamp,,,,,
2024-06-01 00:00:01,WBETHUSDT,3911.94,0.0208,3911.93,0.0127
2024-06-01 00:00:02,WBETHUSDT,3911.94,0.0716,3911.93,0.0127
2024-06-01 00:00:03,WBETHUSDT,3911.94,0.1906,3911.93,0.0127
2024-06-01 00:00:04,WBETHUSDT,3911.94,0.1398,3911.93,0.0127
2024-06-01 00:00:05,WBETHUSDT,3911.94,0.0008,3911.93,0.0462
...,...,...,...,...,...
2024-12-31 23:59:53,WBETHUSDT,3531.79,0.1486,3528.90,0.1780
2024-12-31 23:59:54,WBETHUSDT,3531.79,0.1486,3528.90,0.1780
2024-12-31 23:59:57,WBETHUSDT,3531.77,0.1486,3528.92,0.1780
2024-12-31 23:59:58,WBETHUSDT,3531.77,0.1486,3528.92,0.1780
2024-12-31 23:59:59,WBETHUSDT,3531.75,0.1486,3528.93,0.9383

In [186]:
#resample data to 1 minute
btc_usdt_1m = btc_usdt.resample('1min').agg({
    'asks[0].price': 'last',
    'asks[0].amount': 'last',
    'bids[0].price': 'last',
    'bids[0].amount': 'last'
})

wbtc_usdt_1m = wbtc_usdt.resample('1min').agg({
    'asks[0].price': 'last',
    'asks[0].amount': 'last',
    'bids[0].price': 'last',
    'bids[0].amount': 'last'
})

eth_usdt_1m = eth_usdt.resample('1min').agg({
    'asks[0].price': 'last',
    'asks[0].amount': 'last',
    'bids[0].price': 'last',
    'bids[0].amount': 'last'
})

wbeth_usdt_1m = wbeth_usdt.resample('1min').agg({
    'asks[0].price': 'last',
    'asks[0].amount': 'last',
    'bids[0].price': 'last',
    'bids[0].amount': 'last'
})

In [187]:
eth_usdt_1m

,asks[0].price,asks[0].amount,bids[0].price,bids[0].amount
local_timestamp,,,,
2024-06-01 00:00:00,3765.89,51.4959,3765.88,8.3680
2024-06-01 00:01:00,3763.01,53.8655,3763.00,10.1998
2024-06-01 00:02:00,3764.52,12.6084,3764.51,13.1216
2024-06-01 00:03:00,3765.82,49.6716,3765.81,6.8205
2024-06-01 00:04:00,3766.68,4.0122,3766.67,42.2719
...,...,...,...,...
2024-12-31 23:55:00,3341.74,15.3455,3341.73,52.3086
2024-12-31 23:56:00,3340.65,15.2415,3340.64,11.0570
2024-12-31 23:57:00,3339.35,26.2239,3339.34,4.9053
2024-12-31 23:58:00,3338.42,30.6241,3338.41,13.2310
2024-12-31 23:59:00,3337.79,22.7346,3337.78,4.4490

In [188]:
btc_usdt_1m.isna().sum()
wbtc_usdt_1m.isna().sum()
eth_usdt_1m.isna().sum()
wbeth_usdt_1m.isna().sum()

print(btc_usdt_1m.isna().sum())
print(wbtc_usdt_1m.isna().sum())
print(eth_usdt_1m.isna().sum())
print(wbeth_usdt_1m.isna().sum())

asks[0].price     62
asks[0].amount    62
bids[0].price     62
bids[0].amount    62
dtype: int64
asks[0].price     97
asks[0].amount    97
bids[0].price     97
bids[0].amount    97
dtype: int64
asks[0].price     62
asks[0].amount    62
bids[0].price     62
bids[0].amount    62
dtype: int64
asks[0].price     109
asks[0].amount    109
bids[0].price     109
bids[0].amount    109
dtype: int64

In [189]:
#Drop NaN values
btc_usdt_1m = btc_usdt_1m.dropna()
wbtc_usdt_1m = wbtc_usdt_1m.dropna()
eth_usdt_1m = eth_usdt_1m.dropna()
wbeth_usdt_1m = wbeth_usdt_1m.dropna()

In [190]:
#Calculate mid prices
btc_usdt_1m['mid_price'] = (btc_usdt_1m['asks[0].price'] + btc_usdt_1m['bids[0].price']) / 2
wbtc_usdt_1m['mid_price'] = (wbtc_usdt_1m['asks[0].price'] + wbtc_usdt_1m['bids[0].price']) / 2
eth_usdt_1m['mid_price'] = (eth_usdt_1m['asks[0].price'] + eth_usdt_1m['bids[0].price']) / 2
wbeth_usdt_1m['mid_price'] = (wbeth_usdt_1m['asks[0].price'] + wbeth_usdt_1m['bids[0].price']) / 2

# #Calculate liquidity
btc_usdt_1m['ask_liquidity'] = btc_usdt_1m['asks[0].price'] * btc_usdt_1m['asks[0].amount']
btc_usdt_1m['bid_liquidity'] = btc_usdt_1m['bids[0].price'] * btc_usdt_1m['bids[0].amount']

wbtc_usdt_1m['ask_liquidity'] = wbtc_usdt_1m['asks[0].price'] * wbtc_usdt_1m['asks[0].amount']
wbtc_usdt_1m['bid_liquidity'] = wbtc_usdt_1m['bids[0].price'] * wbtc_usdt_1m['bids[0].amount']

eth_usdt_1m['ask_liquidity'] = eth_usdt_1m['asks[0].price'] * eth_usdt_1m['asks[0].amount']
eth_usdt_1m['bid_liquidity'] = eth_usdt_1m['bids[0].price'] * eth_usdt_1m['bids[0].amount']

wbeth_usdt_1m['ask_liquidity'] = wbeth_usdt_1m['asks[0].price'] * wbeth_usdt_1m['asks[0].amount']
wbeth_usdt_1m['bid_liquidity'] = wbeth_usdt_1m['bids[0].price'] * wbeth_usdt_1m['bids[0].amount']

/var/folders/v0/xxx_2wqx4qsc_858pvgmg3_m0000gp/T/ipykernel_55897/143750665.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eth_usdt_1m['mid_price'] = (eth_usdt_1m['asks[0].price'] + eth_usdt_1m['bids[0].price']) / 2
/var/folders/v0/xxx_2wqx4qsc_858pvgmg3_m0000gp/T/ipykernel_55897/143750665.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eth_usdt_1m['ask_liquidity'] = eth_usdt_1m['asks[0].price'] * eth_usdt_1m['asks[0].amount']
/var/folders/v0/xxx_2wqx4qsc_858pvgmg3_m0000gp/T/ipykernel_55897/143750665.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eth_usdt_1m['bid_liquidity'] = eth_usdt_1m['bids[0].price'] * eth_usdt_1m['bids[0].amount']

In [191]:
btc_usdt_1m

,asks[0].price,asks[0].amount,bids[0].price,bids[0].amount,mid_price,ask_liquidity,bid_liquidity
local_timestamp,,,,,,,
2024-06-01 00:00:00,67573.41,2.16203,67573.40,2.92442,67573.405,146095.739622,197613.002428
2024-06-01 00:01:00,67564.65,2.82680,67564.64,4.38154,67564.645,190991.752620,296037.172746
2024-06-01 00:02:00,67582.90,2.00250,67582.89,6.07325,67582.895,135334.757250,410447.786692
2024-06-01 00:03:00,67612.55,2.46055,67612.54,3.03296,67612.545,166364.059903,205066.129318
2024-06-01 00:04:00,67647.88,0.86846,67647.87,5.44865,67647.875,58749.477865,368589.566875
...,...,...,...,...,...,...,...
2024-12-31 23:55:00,93667.52,0.50583,93667.51,4.99400,93667.515,47379.841642,467775.544940
2024-12-31 23:56:00,93636.38,3.95422,93636.37,0.42281,93636.375,370258.846524,39590.393600
2024-12-31 23:57:00,93616.05,3.09142,93616.04,0.10012,93616.045,289406.529291,9372.837925
2024-12-31 23:58:00,93600.01,3.26564,93600.00,1.56922,93600.005,305663.936656,146878.992000
2024-12-31 23:59:00,93576.01,3.52974,93576.00,0.61202,93576.005,330298.985537,57270.383520

In [192]:

#Remove columns before merging

#Bitcoin
#--------------------------------------------------------------
btc_mid_price = btc_usdt_1m['mid_price'].rename('btc_mid_price')
wbtc_mid_price = wbtc_usdt_1m['mid_price'].rename('wbtc_mid_price')

btc_ask_price = btc_usdt_1m['asks[0].price'].rename('btc_ask_price')
btc_bid_price = btc_usdt_1m['bids[0].price'].rename('btc_bid_price')

wbtc_ask_price = wbtc_usdt_1m['asks[0].price'].rename('wbtc_ask_price')
wbtc_bid_price = wbtc_usdt_1m['bids[0].price'].rename('wbtc_bid_price')

btc_ask_liquidity = btc_usdt_1m['ask_liquidity'].rename('btc_ask_liquidity')
btc_bid_liquidity = btc_usdt_1m['bid_liquidity'].rename('btc_bid_liquidity')

wbtc_ask_liquidity = wbtc_usdt_1m['ask_liquidity'].rename('wbtc_ask_liquidity')
wbtc_bid_liquidity = wbtc_usdt_1m['bid_liquidity'].rename('wbtc_bid_liquidity')
#--------------------------------------------------------------


#Ethereum
#--------------------------------------------------------------
eth_mid_price = eth_usdt_1m['mid_price'].rename('eth_mid_price')
wbeth_mid_price = wbeth_usdt_1m['mid_price'].rename('wbeth_mid_price')

eth_ask_price = eth_usdt_1m['asks[0].price'].rename('eth_ask_price')
eth_bid_price = eth_usdt_1m['bids[0].price'].rename('eth_bid_price')

wbeth_ask_price = wbeth_usdt_1m['asks[0].price'].rename('wbeth_ask_price')
wbeth_bid_price = wbeth_usdt_1m['bids[0].price'].rename('wbeth_bid_price')

eth_ask_liquidity = eth_usdt_1m['ask_liquidity'].rename('eth_ask_liquidity')
eth_bid_liquidity = eth_usdt_1m['bid_liquidity'].rename('eth_bid_liquidity')

wbeth_ask_liquidity = wbeth_usdt_1m['ask_liquidity'].rename('wbeth_ask_liquidity')
wbeth_bid_liquidity = wbeth_usdt_1m['bid_liquidity'].rename('wbeth_bid_liquidity')
#--------------------------------------------------------------

In [193]:

#Merge dataframes

btc = pd.concat([btc_mid_price, btc_ask_price, btc_bid_price, btc_ask_liquidity, btc_bid_liquidity], axis=1)
wbtc = pd.concat([wbtc_mid_price, wbtc_ask_price, wbtc_bid_price, wbtc_ask_liquidity, wbtc_bid_liquidity], axis=1)

eth = pd.concat([eth_mid_price, eth_ask_price, eth_bid_price, eth_ask_liquidity, eth_bid_liquidity], axis=1)
wbeth = pd.concat([wbeth_mid_price, wbeth_ask_price, wbeth_bid_price, wbeth_ask_liquidity, wbeth_bid_liquidity], axis=1)

#Reset index so that the local_timestamp is a column and not the index for merging
btc = btc.reset_index()
wbtc = wbtc.reset_index()

eth = eth.reset_index()
wbeth = wbeth.reset_index()

btc_wbtc_combined_1m = pd.merge(btc, wbtc, on='local_timestamp', how='inner')
btc_wbtc_combined_1m.set_index('local_timestamp', inplace=True) #restore datetime index

eth_wbeth_combined_1m = pd.merge(eth, wbeth, on='local_timestamp', how='inner')
eth_wbeth_combined_1m.set_index('local_timestamp', inplace=True) #restore datetime index

In [194]:
wbtc_usdt_1m

,asks[0].price,asks[0].amount,bids[0].price,bids[0].amount,mid_price,ask_liquidity,bid_liquidity
local_timestamp,,,,,,,
2024-06-01 00:00:00,67593.19,0.00191,67541.42,0.01036,67567.305,129.102993,699.729111
2024-06-01 00:01:00,67584.53,0.00412,67516.14,0.01036,67550.335,278.448264,699.467210
2024-06-01 00:02:00,67593.10,0.00327,67578.94,0.01035,67586.020,221.029437,699.442029
2024-06-01 00:03:00,67641.89,0.00192,67617.17,0.00959,67629.530,129.872429,648.448660
2024-06-01 00:04:00,67664.68,0.00067,67656.47,0.00590,67660.575,45.335336,399.173173
...,...,...,...,...,...,...,...
2024-12-31 23:55:00,93518.50,0.00062,93345.55,0.09365,93432.025,57.981470,8741.810757
2024-12-31 23:56:00,93530.73,0.00062,93466.12,0.00466,93498.425,57.989053,435.552119
2024-12-31 23:57:00,93446.86,0.04140,93446.85,0.04140,93446.855,3868.700004,3868.699590
2024-12-31 23:58:00,93457.01,0.06164,93457.00,0.04560,93457.005,5760.690096,4261.639200
2024-12-31 23:59:00,93443.94,0.04530,93443.93,0.00407,93443.935,4233.010482,380.316795

In [195]:
btc_wbtc_combined_1m

,btc_mid_price,btc_ask_price,btc_bid_price,btc_ask_liquidity,btc_bid_liquidity,wbtc_mid_price,wbtc_ask_price,wbtc_bid_price,wbtc_ask_liquidity,wbtc_bid_liquidity
local_timestamp,,,,,,,,,,
2024-06-01 00:00:00,67573.405,67573.41,67573.40,146095.739622,197613.002428,67567.305,67593.19,67541.42,129.102993,699.729111
2024-06-01 00:01:00,67564.645,67564.65,67564.64,190991.752620,296037.172746,67550.335,67584.53,67516.14,278.448264,699.467210
2024-06-01 00:02:00,67582.895,67582.90,67582.89,135334.757250,410447.786692,67586.020,67593.10,67578.94,221.029437,699.442029
2024-06-01 00:03:00,67612.545,67612.55,67612.54,166364.059903,205066.129318,67629.530,67641.89,67617.17,129.872429,648.448660
2024-06-01 00:04:00,67647.875,67647.88,67647.87,58749.477865,368589.566875,67660.575,67664.68,67656.47,45.335336,399.173173
...,...,...,...,...,...,...,...,...,...,...
2024-12-31 23:55:00,93667.515,93667.52,93667.51,47379.841642,467775.544940,93432.025,93518.50,93345.55,57.981470,8741.810757
2024-12-31 23:56:00,93636.375,93636.38,93636.37,370258.846524,39590.393600,93498.425,93530.73,93466.12,57.989053,435.552119
2024-12-31 23:57:00,93616.045,93616.05,93616.04,289406.529291,9372.837925,93446.855,93446.86,93446.85,3868.700004,3868.699590
2024-12-31 23:58:00,93600.005,93600.01,93600.00,305663.936656,146878.992000,93457.005,93457.01,93457.00,5760.690096,4261.639200
2024-12-31 23:59:00,93576.005,93576.01,93576.00,330298.985537,57270.383520,93443.935,93443.94,93443.93,4233.010482,380.316795

In [201]:
eth_usdt_1m

,asks[0].price,asks[0].amount,bids[0].price,bids[0].amount,mid_price,ask_liquidity,bid_liquidity
local_timestamp,,,,,,,
2024-06-01 00:00:00,3765.89,51.4959,3765.88,8.3680,3765.885,193927.894851,31512.883840
2024-06-01 00:01:00,3763.01,53.8655,3763.00,10.1998,3763.005,202696.415155,38381.847400
2024-06-01 00:02:00,3764.52,12.6084,3764.51,13.1216,3764.515,47464.573968,49396.394416
2024-06-01 00:03:00,3765.82,49.6716,3765.81,6.8205,3765.815,187054.304712,25684.707105
2024-06-01 00:04:00,3766.68,4.0122,3766.67,42.2719,3766.675,15112.673496,159224.297573
...,...,...,...,...,...,...,...
2024-12-31 23:55:00,3341.74,15.3455,3341.73,52.3086,3341.735,51280.671170,174801.217878
2024-12-31 23:56:00,3340.65,15.2415,3340.64,11.0570,3340.645,50916.516975,36937.456480
2024-12-31 23:57:00,3339.35,26.2239,3339.34,4.9053,3339.345,87570.780465,16380.464502
2024-12-31 23:58:00,3338.42,30.6241,3338.41,13.2310,3338.415,102236.107922,44170.502710
2024-12-31 23:59:00,3337.79,22.7346,3337.78,4.4490,3337.785,75883.320534,14849.783220

In [196]:
eth_wbeth_combined_1m

,eth_mid_price,eth_ask_price,eth_bid_price,eth_ask_liquidity,eth_bid_liquidity,wbeth_mid_price,wbeth_ask_price,wbeth_bid_price,wbeth_ask_liquidity,wbeth_bid_liquidity
local_timestamp,,,,,,,,,,
2024-06-01 00:00:00,3765.885,3765.89,3765.88,193927.894851,31512.883840,3916.525,3916.53,3916.52,386.953164,14.491124
2024-06-01 00:01:00,3763.005,3763.01,3763.00,202696.415155,38381.847400,3912.750,3914.47,3911.03,659.196748,49.670081
2024-06-01 00:02:00,3764.515,3764.52,3764.51,47464.573968,49396.394416,3915.350,3915.42,3915.28,9.788550,11.354312
2024-06-01 00:03:00,3765.815,3765.82,3765.81,187054.304712,25684.707105,3916.765,3917.23,3916.30,229.549678,49.737010
2024-06-01 00:04:00,3766.675,3766.68,3766.67,15112.673496,159224.297573,3918.100,3918.32,3917.88,170.446920,62.686080
...,...,...,...,...,...,...,...,...,...,...
2024-12-31 23:55:00,3341.735,3341.74,3341.73,51280.671170,174801.217878,3534.665,3535.72,3533.61,405.547084,120.142740
2024-12-31 23:56:00,3340.645,3340.65,3340.64,50916.516975,36937.456480,3533.665,3534.77,3532.56,405.438119,2720.071200
2024-12-31 23:57:00,3339.345,3339.35,3339.34,87570.780465,16380.464502,3532.305,3533.44,3531.17,405.285568,2815.754958
2024-12-31 23:58:00,3338.415,3338.42,3338.41,102236.107922,44170.502710,3531.890,3532.86,3530.92,524.982996,27.188084
2024-12-31 23:59:00,3337.785,3337.79,3337.78,75883.320534,14849.783220,3530.340,3531.75,3528.93,524.818050,3311.195019

In [197]:
btc_wbtc_combined_1m.isna().sum()

btc_mid_price         0
btc_ask_price         0
btc_bid_price         0
btc_ask_liquidity     0
btc_bid_liquidity     0
wbtc_mid_price        0
wbtc_ask_price        0
wbtc_bid_price        0
wbtc_ask_liquidity    0
wbtc_bid_liquidity    0
dtype: int64

In [198]:
eth_wbeth_combined_1m.isna().sum()

eth_mid_price          0
eth_ask_price          0
eth_bid_price          0
eth_ask_liquidity      0
eth_bid_liquidity      0
wbeth_mid_price        0
wbeth_ask_price        0
wbeth_bid_price        0
wbeth_ask_liquidity    0
wbeth_bid_liquidity    0
dtype: int64

In [200]:
btc_wbtc_combined_1m.to_csv('order_book_data/merged_data/1min/btc_wbtc_combined_1m.csv')
eth_wbeth_combined_1m.to_csv('order_book_data/merged_data/1min/eth_wbeth_combined_1m.csv')

In [174]:
# btc_new_data = pd.read_csv('order_book_data/6month_LOB_2024__BTCUSDT.csv')

In [ ]:
# btc_new_data