In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

/Users/alex_1/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

# Pre Processing
---

In [2]:
btc_usdt = pd.read_csv('order_book_data/BTCUSDT_1s.csv')
wbtc_usdt = pd.read_csv('order_book_data/WBTCUSDT_1s.csv')
eth_usdt = pd.read_csv('order_book_data/ETHUSDT_1s.csv')
wbeth_usdt = pd.read_csv('order_book_data/WBETHUSDT_1s.csv')

In [3]:
#Order by local_timestamp
btc_usdt = btc_usdt.sort_values(by='local_timestamp')
wbtc_usdt = wbtc_usdt.sort_values(by='local_timestamp')
eth_usdt = eth_usdt.sort_values(by='local_timestamp')
wbeth_usdt = wbeth_usdt.sort_values(by='local_timestamp')


#Drop Unamed column
btc_usdt = btc_usdt.drop(columns=['Unnamed: 0'])
wbtc_usdt = wbtc_usdt.drop(columns=['Unnamed: 0'])
eth_usdt = eth_usdt.drop(columns=['Unnamed: 0'])
wbeth_usdt = wbeth_usdt.drop(columns=['Unnamed: 0'])

#Convert local_timestamp to datetime
btc_usdt['local_timestamp'] = pd.to_datetime(btc_usdt['local_timestamp'])
wbtc_usdt['local_timestamp'] = pd.to_datetime(wbtc_usdt['local_timestamp'])
eth_usdt['local_timestamp'] = pd.to_datetime(eth_usdt['local_timestamp'])
wbeth_usdt['local_timestamp'] = pd.to_datetime(wbeth_usdt['local_timestamp'])

#Set local_timestamp as index
btc_usdt = btc_usdt.set_index('local_timestamp')
wbtc_usdt = wbtc_usdt.set_index('local_timestamp')
eth_usdt = eth_usdt.set_index('local_timestamp')
wbeth_usdt = wbeth_usdt.set_index('local_timestamp')

In [4]:
btc_usdt

,symbol,asks[0].price,asks[0].amount,bids[0].price,bids[0].amount
local_timestamp,,,,,
2024-06-01 00:00:00,BTCUSDT,67547.76,0.34897,67547.75,3.27941
2024-06-01 00:00:01,BTCUSDT,67547.76,0.85531,67547.75,6.69047
2024-06-01 00:00:02,BTCUSDT,67547.76,0.84523,67547.75,6.80568
2024-06-01 00:00:03,BTCUSDT,67547.76,0.79983,67547.75,6.80568
2024-06-01 00:00:04,BTCUSDT,67547.76,0.42881,67547.75,7.11088
...,...,...,...,...,...
2024-12-31 23:59:55,BTCUSDT,93576.01,3.96097,93576.00,0.56225
2024-12-31 23:59:56,BTCUSDT,93576.01,3.96097,93576.00,0.56245
2024-12-31 23:59:57,BTCUSDT,93576.01,4.17420,93576.00,0.35615
2024-12-31 23:59:58,BTCUSDT,93576.01,4.31092,93576.00,0.35545
2024-12-31 23:59:59,BTCUSDT,93576.01,3.52974,93576.00,0.61202

In [5]:
#Filter date range to 2024-06-01 to 2024-12-31 
btc_usdt = btc_usdt.loc['2024-06-01':'2024-12-31']
wbtc_usdt = wbtc_usdt.loc['2024-06-01':'2024-12-31']
eth_usdt = eth_usdt.loc['2024-06-01':'2024-12-31']
wbeth_usdt = wbeth_usdt.loc['2024-06-01':'2024-12-31']

In [6]:
eth_usdt

,symbol,asks[0].price,asks[0].amount,bids[0].price,bids[0].amount
local_timestamp,,,,,
2024-06-01 00:00:02,ETHUSDT,3762.70,5.9667,3762.69,52.6466
2024-06-01 00:00:03,ETHUSDT,3762.70,5.8263,3762.69,52.6677
2024-06-01 00:00:04,ETHUSDT,3762.70,5.8013,3762.69,56.9970
2024-06-01 00:00:05,ETHUSDT,3763.07,26.8783,3763.06,59.8217
2024-06-01 00:00:06,ETHUSDT,3763.33,5.7079,3763.32,40.4943
...,...,...,...,...,...
2024-12-31 23:59:55,ETHUSDT,3337.79,22.0972,3337.78,5.9750
2024-12-31 23:59:56,ETHUSDT,3337.79,21.7644,3337.78,5.9552
2024-12-31 23:59:57,ETHUSDT,3337.79,21.7707,3337.78,5.9545
2024-12-31 23:59:58,ETHUSDT,3337.79,26.0538,3337.78,2.9058
2024-12-31 23:59:59,ETHUSDT,3337.79,22.7346,3337.78,4.4490

In [7]:
wbeth_usdt

,symbol,asks[0].price,asks[0].amount,bids[0].price,bids[0].amount
local_timestamp,,,,,
2024-06-01 00:00:01,WBETHUSDT,3911.94,0.0208,3911.93,0.0127
2024-06-01 00:00:02,WBETHUSDT,3911.94,0.0716,3911.93,0.0127
2024-06-01 00:00:03,WBETHUSDT,3911.94,0.1906,3911.93,0.0127
2024-06-01 00:00:04,WBETHUSDT,3911.94,0.1398,3911.93,0.0127
2024-06-01 00:00:05,WBETHUSDT,3911.94,0.0008,3911.93,0.0462
...,...,...,...,...,...
2024-12-31 23:59:53,WBETHUSDT,3531.79,0.1486,3528.90,0.1780
2024-12-31 23:59:54,WBETHUSDT,3531.79,0.1486,3528.90,0.1780
2024-12-31 23:59:57,WBETHUSDT,3531.77,0.1486,3528.92,0.1780
2024-12-31 23:59:58,WBETHUSDT,3531.77,0.1486,3528.92,0.1780
2024-12-31 23:59:59,WBETHUSDT,3531.75,0.1486,3528.93,0.9383

In [8]:
#resample data to 1 minute
btc_usdt_1m = btc_usdt.resample('1min').agg({
    'asks[0].price': 'last',
    'asks[0].amount': 'last',
    'bids[0].price': 'last',
    'bids[0].amount': 'last'
})

wbtc_usdt_1m = wbtc_usdt.resample('1min').agg({
    'asks[0].price': 'last',
    'asks[0].amount': 'last',
    'bids[0].price': 'last',
    'bids[0].amount': 'last'
})

eth_usdt_1m = eth_usdt.resample('1min').agg({
    'asks[0].price': 'last',
    'asks[0].amount': 'last',
    'bids[0].price': 'last',
    'bids[0].amount': 'last'
})

wbeth_usdt_1m = wbeth_usdt.resample('1min').agg({
    'asks[0].price': 'last',
    'asks[0].amount': 'last',
    'bids[0].price': 'last',
    'bids[0].amount': 'last'
})

In [9]:
eth_usdt_1m

,asks[0].price,asks[0].amount,bids[0].price,bids[0].amount
local_timestamp,,,,
2024-06-01 00:00:00,3765.89,51.4959,3765.88,8.3680
2024-06-01 00:01:00,3763.01,53.8655,3763.00,10.1998
2024-06-01 00:02:00,3764.52,12.6084,3764.51,13.1216
2024-06-01 00:03:00,3765.82,49.6716,3765.81,6.8205
2024-06-01 00:04:00,3766.68,4.0122,3766.67,42.2719
...,...,...,...,...
2024-12-31 23:55:00,3341.74,15.3455,3341.73,52.3086
2024-12-31 23:56:00,3340.65,15.2415,3340.64,11.0570
2024-12-31 23:57:00,3339.35,26.2239,3339.34,4.9053
2024-12-31 23:58:00,3338.42,30.6241,3338.41,13.2310
2024-12-31 23:59:00,3337.79,22.7346,3337.78,4.4490

In [10]:
btc_usdt_1m.isna().sum()
wbtc_usdt_1m.isna().sum()
eth_usdt_1m.isna().sum()
wbeth_usdt_1m.isna().sum()

print(btc_usdt_1m.isna().sum())
print(wbtc_usdt_1m.isna().sum())
print(eth_usdt_1m.isna().sum())
print(wbeth_usdt_1m.isna().sum())

asks[0].price     62
asks[0].amount    62
bids[0].price     62
bids[0].amount    62
dtype: int64
asks[0].price     97
asks[0].amount    97
bids[0].price     97
bids[0].amount    97
dtype: int64
asks[0].price     62
asks[0].amount    62
bids[0].price     62
bids[0].amount    62
dtype: int64
asks[0].price     109
asks[0].amount    109
bids[0].price     109
bids[0].amount    109
dtype: int64

In [11]:
#Drop NaN values
btc_usdt_1m = btc_usdt_1m.dropna()
wbtc_usdt_1m = wbtc_usdt_1m.dropna()
eth_usdt_1m = eth_usdt_1m.dropna()
wbeth_usdt_1m = wbeth_usdt_1m.dropna()

In [12]:
#Calculate mid prices
btc_usdt_1m['mid_price'] = (btc_usdt_1m['asks[0].price'] + btc_usdt_1m['bids[0].price']) / 2
wbtc_usdt_1m['mid_price'] = (wbtc_usdt_1m['asks[0].price'] + wbtc_usdt_1m['bids[0].price']) / 2
eth_usdt_1m['mid_price'] = (eth_usdt_1m['asks[0].price'] + eth_usdt_1m['bids[0].price']) / 2
wbeth_usdt_1m['mid_price'] = (wbeth_usdt_1m['asks[0].price'] + wbeth_usdt_1m['bids[0].price']) / 2

# # #Calculate liquidity
# btc_usdt_1m['ask_liquidity'] = btc_usdt_1m['asks[0].price'] * btc_usdt_1m['asks[0].amount']
# btc_usdt_1m['bid_liquidity'] = btc_usdt_1m['bids[0].price'] * btc_usdt_1m['bids[0].amount']

# wbtc_usdt_1m['ask_liquidity'] = wbtc_usdt_1m['asks[0].price'] * wbtc_usdt_1m['asks[0].amount']
# wbtc_usdt_1m['bid_liquidity'] = wbtc_usdt_1m['bids[0].price'] * wbtc_usdt_1m['bids[0].amount']

# eth_usdt_1m['ask_liquidity'] = eth_usdt_1m['asks[0].price'] * eth_usdt_1m['asks[0].amount']
# eth_usdt_1m['bid_liquidity'] = eth_usdt_1m['bids[0].price'] * eth_usdt_1m['bids[0].amount']

# wbeth_usdt_1m['ask_liquidity'] = wbeth_usdt_1m['asks[0].price'] * wbeth_usdt_1m['asks[0].amount']
# wbeth_usdt_1m['bid_liquidity'] = wbeth_usdt_1m['bids[0].price'] * wbeth_usdt_1m['bids[0].amount']

/var/folders/rc/tn2ys5g55157vhhlmn0_vfwr0000gq/T/ipykernel_1373/174462433.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eth_usdt_1m['mid_price'] = (eth_usdt_1m['asks[0].price'] + eth_usdt_1m['bids[0].price']) / 2

In [13]:
btc_usdt_1m

,asks[0].price,asks[0].amount,bids[0].price,bids[0].amount,mid_price
local_timestamp,,,,,
2024-06-01 00:00:00,67573.41,2.16203,67573.40,2.92442,67573.405
2024-06-01 00:01:00,67564.65,2.82680,67564.64,4.38154,67564.645
2024-06-01 00:02:00,67582.90,2.00250,67582.89,6.07325,67582.895
2024-06-01 00:03:00,67612.55,2.46055,67612.54,3.03296,67612.545
2024-06-01 00:04:00,67647.88,0.86846,67647.87,5.44865,67647.875
...,...,...,...,...,...
2024-12-31 23:55:00,93667.52,0.50583,93667.51,4.99400,93667.515
2024-12-31 23:56:00,93636.38,3.95422,93636.37,0.42281,93636.375
2024-12-31 23:57:00,93616.05,3.09142,93616.04,0.10012,93616.045
2024-12-31 23:58:00,93600.01,3.26564,93600.00,1.56922,93600.005
2024-12-31 23:59:00,93576.01,3.52974,93576.00,0.61202,93576.005

In [14]:

#Remove columns before merging

#Bitcoin
#--------------------------------------------------------------
btc_mid_price = btc_usdt_1m['mid_price'].rename('btc_mid_price')
wbtc_mid_price = wbtc_usdt_1m['mid_price'].rename('wbtc_mid_price')

btc_ask_price = btc_usdt_1m['asks[0].price'].rename('btc_ask_price')
btc_bid_price = btc_usdt_1m['bids[0].price'].rename('btc_bid_price')

wbtc_ask_price = wbtc_usdt_1m['asks[0].price'].rename('wbtc_ask_price')
wbtc_bid_price = wbtc_usdt_1m['bids[0].price'].rename('wbtc_bid_price')

btc_ask_amount = btc_usdt_1m['asks[0].amount'].rename('btc_ask_amount')
btc_bid_amount = btc_usdt_1m['bids[0].amount'].rename('btc_bid_amount')

wbtc_ask_amount = wbtc_usdt_1m['asks[0].amount'].rename('wbtc_ask_amount')
wbtc_bid_amount = wbtc_usdt_1m['bids[0].amount'].rename('wbtc_bid_amount')

# btc_ask_liquidity = btc_usdt_1m['ask_liquidity'].rename('btc_ask_liquidity')
# btc_bid_liquidity = btc_usdt_1m['bid_liquidity'].rename('btc_bid_liquidity')

# wbtc_ask_liquidity = wbtc_usdt_1m['ask_liquidity'].rename('wbtc_ask_liquidity')
# wbtc_bid_liquidity = wbtc_usdt_1m['bid_liquidity'].rename('wbtc_bid_liquidity')
#--------------------------------------------------------------


#Ethereum
#--------------------------------------------------------------
eth_mid_price = eth_usdt_1m['mid_price'].rename('eth_mid_price')
wbeth_mid_price = wbeth_usdt_1m['mid_price'].rename('wbeth_mid_price')

eth_ask_price = eth_usdt_1m['asks[0].price'].rename('eth_ask_price')
eth_bid_price = eth_usdt_1m['bids[0].price'].rename('eth_bid_price')

wbeth_ask_price = wbeth_usdt_1m['asks[0].price'].rename('wbeth_ask_price')
wbeth_bid_price = wbeth_usdt_1m['bids[0].price'].rename('wbeth_bid_price')

eth_ask_amount = eth_usdt_1m['asks[0].amount'].rename('eth_ask_amount')
eth_bid_amount = eth_usdt_1m['bids[0].amount'].rename('eth_bid_amount')

wbeth_ask_amount = wbeth_usdt_1m['asks[0].amount'].rename('wbeth_ask_amount')
wbeth_bid_amount = wbeth_usdt_1m['bids[0].amount'].rename('wbeth_bid_amount') 

# eth_ask_liquidity = eth_usdt_1m['ask_liquidity'].rename('eth_ask_liquidity')
# eth_bid_liquidity = eth_usdt_1m['bid_liquidity'].rename('eth_bid_liquidity')

# wbeth_ask_liquidity = wbeth_usdt_1m['ask_liquidity'].rename('wbeth_ask_liquidity')
# wbeth_bid_liquidity = wbeth_usdt_1m['bid_liquidity'].rename('wbeth_bid_liquidity')
#--------------------------------------------------------------

In [15]:

#Merge dataframes

btc = pd.concat([btc_mid_price, btc_ask_price, btc_bid_price, btc_ask_amount, btc_bid_amount], axis=1)
wbtc = pd.concat([wbtc_mid_price, wbtc_ask_price, wbtc_bid_price, wbtc_ask_amount, wbtc_bid_amount], axis=1)

eth = pd.concat([eth_mid_price, eth_ask_price, eth_bid_price, eth_ask_amount, eth_bid_amount], axis=1)
wbeth = pd.concat([wbeth_mid_price, wbeth_ask_price, wbeth_bid_price, wbeth_ask_amount, wbeth_bid_amount], axis=1)

#Reset index so that the local_timestamp is a column and not the index for merging
btc = btc.reset_index()
wbtc = wbtc.reset_index()

eth = eth.reset_index()
wbeth = wbeth.reset_index()

btc_wbtc_combined_1m = pd.merge(btc, wbtc, on='local_timestamp', how='inner')
btc_wbtc_combined_1m.set_index('local_timestamp', inplace=True) #restore datetime index

eth_wbeth_combined_1m = pd.merge(eth, wbeth, on='local_timestamp', how='inner')
eth_wbeth_combined_1m.set_index('local_timestamp', inplace=True) #restore datetime index

In [16]:
wbtc_usdt_1m

,asks[0].price,asks[0].amount,bids[0].price,bids[0].amount,mid_price
local_timestamp,,,,,
2024-06-01 00:00:00,67593.19,0.00191,67541.42,0.01036,67567.305
2024-06-01 00:01:00,67584.53,0.00412,67516.14,0.01036,67550.335
2024-06-01 00:02:00,67593.10,0.00327,67578.94,0.01035,67586.020
2024-06-01 00:03:00,67641.89,0.00192,67617.17,0.00959,67629.530
2024-06-01 00:04:00,67664.68,0.00067,67656.47,0.00590,67660.575
...,...,...,...,...,...
2024-12-31 23:55:00,93518.50,0.00062,93345.55,0.09365,93432.025
2024-12-31 23:56:00,93530.73,0.00062,93466.12,0.00466,93498.425
2024-12-31 23:57:00,93446.86,0.04140,93446.85,0.04140,93446.855
2024-12-31 23:58:00,93457.01,0.06164,93457.00,0.04560,93457.005
2024-12-31 23:59:00,93443.94,0.04530,93443.93,0.00407,93443.935

In [27]:
wbtc_usdt_1m

,asks[0].price,asks[0].amount,bids[0].price,bids[0].amount,mid_price
local_timestamp,,,,,
2024-06-01 00:00:00,67593.19,0.00191,67541.42,0.01036,67567.305
2024-06-01 00:01:00,67584.53,0.00412,67516.14,0.01036,67550.335
2024-06-01 00:02:00,67593.10,0.00327,67578.94,0.01035,67586.020
2024-06-01 00:03:00,67641.89,0.00192,67617.17,0.00959,67629.530
2024-06-01 00:04:00,67664.68,0.00067,67656.47,0.00590,67660.575
...,...,...,...,...,...
2024-12-31 23:55:00,93518.50,0.00062,93345.55,0.09365,93432.025
2024-12-31 23:56:00,93530.73,0.00062,93466.12,0.00466,93498.425
2024-12-31 23:57:00,93446.86,0.04140,93446.85,0.04140,93446.855
2024-12-31 23:58:00,93457.01,0.06164,93457.00,0.04560,93457.005
2024-12-31 23:59:00,93443.94,0.04530,93443.93,0.00407,93443.935

In [17]:
btc_wbtc_combined_1m

,btc_mid_price,btc_ask_price,btc_bid_price,btc_ask_amount,btc_bid_amount,wbtc_mid_price,wbtc_ask_price,wbtc_bid_price,wbtc_ask_amount,wbtc_bid_amount
local_timestamp,,,,,,,,,,
2024-06-01 00:00:00,67573.405,67573.41,67573.40,2.16203,2.92442,67567.305,67593.19,67541.42,0.00191,0.01036
2024-06-01 00:01:00,67564.645,67564.65,67564.64,2.82680,4.38154,67550.335,67584.53,67516.14,0.00412,0.01036
2024-06-01 00:02:00,67582.895,67582.90,67582.89,2.00250,6.07325,67586.020,67593.10,67578.94,0.00327,0.01035
2024-06-01 00:03:00,67612.545,67612.55,67612.54,2.46055,3.03296,67629.530,67641.89,67617.17,0.00192,0.00959
2024-06-01 00:04:00,67647.875,67647.88,67647.87,0.86846,5.44865,67660.575,67664.68,67656.47,0.00067,0.00590
...,...,...,...,...,...,...,...,...,...,...
2024-12-31 23:55:00,93667.515,93667.52,93667.51,0.50583,4.99400,93432.025,93518.50,93345.55,0.00062,0.09365
2024-12-31 23:56:00,93636.375,93636.38,93636.37,3.95422,0.42281,93498.425,93530.73,93466.12,0.00062,0.00466
2024-12-31 23:57:00,93616.045,93616.05,93616.04,3.09142,0.10012,93446.855,93446.86,93446.85,0.04140,0.04140
2024-12-31 23:58:00,93600.005,93600.01,93600.00,3.26564,1.56922,93457.005,93457.01,93457.00,0.06164,0.04560
2024-12-31 23:59:00,93576.005,93576.01,93576.00,3.52974,0.61202,93443.935,93443.94,93443.93,0.04530,0.00407

In [28]:
wbeth_usdt_1m

,asks[0].price,asks[0].amount,bids[0].price,bids[0].amount,mid_price
local_timestamp,,,,,
2024-06-01 00:00:00,3916.53,0.0988,3916.52,0.0037,3916.525
2024-06-01 00:01:00,3914.47,0.1684,3911.03,0.0127,3912.750
2024-06-01 00:02:00,3915.42,0.0025,3915.28,0.0029,3915.350
2024-06-01 00:03:00,3917.23,0.0586,3916.30,0.0127,3916.765
2024-06-01 00:04:00,3918.32,0.0435,3917.88,0.0160,3918.100
...,...,...,...,...,...
2024-12-31 23:55:00,3535.72,0.1147,3533.61,0.0340,3534.665
2024-12-31 23:56:00,3534.77,0.1147,3532.56,0.7700,3533.665
2024-12-31 23:57:00,3533.44,0.1147,3531.17,0.7974,3532.305
2024-12-31 23:58:00,3532.86,0.1486,3530.92,0.0077,3531.890
2024-12-31 23:59:00,3531.75,0.1486,3528.93,0.9383,3530.340

In [29]:
eth_wbeth_combined_1m

,eth_mid_price,eth_ask_price,eth_bid_price,eth_ask_amount,eth_bid_amount,wbeth_mid_price,wbeth_ask_price,wbeth_bid_price,wbeth_ask_amount,wbeth_bid_amount
local_timestamp,,,,,,,,,,
2024-06-01 00:00:00,3765.885,3765.89,3765.88,51.4959,8.3680,3916.525,3916.53,3916.52,0.0988,0.0037
2024-06-01 00:01:00,3763.005,3763.01,3763.00,53.8655,10.1998,3912.750,3914.47,3911.03,0.1684,0.0127
2024-06-01 00:02:00,3764.515,3764.52,3764.51,12.6084,13.1216,3915.350,3915.42,3915.28,0.0025,0.0029
2024-06-01 00:03:00,3765.815,3765.82,3765.81,49.6716,6.8205,3916.765,3917.23,3916.30,0.0586,0.0127
2024-06-01 00:04:00,3766.675,3766.68,3766.67,4.0122,42.2719,3918.100,3918.32,3917.88,0.0435,0.0160
...,...,...,...,...,...,...,...,...,...,...
2024-12-31 23:55:00,3341.735,3341.74,3341.73,15.3455,52.3086,3534.665,3535.72,3533.61,0.1147,0.0340
2024-12-31 23:56:00,3340.645,3340.65,3340.64,15.2415,11.0570,3533.665,3534.77,3532.56,0.1147,0.7700
2024-12-31 23:57:00,3339.345,3339.35,3339.34,26.2239,4.9053,3532.305,3533.44,3531.17,0.1147,0.7974
2024-12-31 23:58:00,3338.415,3338.42,3338.41,30.6241,13.2310,3531.890,3532.86,3530.92,0.1486,0.0077
2024-12-31 23:59:00,3337.785,3337.79,3337.78,22.7346,4.4490,3530.340,3531.75,3528.93,0.1486,0.9383

In [20]:
btc_wbtc_combined_1m.isna().sum()

btc_mid_price      0
btc_ask_price      0
btc_bid_price      0
btc_ask_amount     0
btc_bid_amount     0
wbtc_mid_price     0
wbtc_ask_price     0
wbtc_bid_price     0
wbtc_ask_amount    0
wbtc_bid_amount    0
dtype: int64

In [21]:
eth_wbeth_combined_1m.isna().sum()

eth_mid_price       0
eth_ask_price       0
eth_bid_price       0
eth_ask_amount      0
eth_bid_amount      0
wbeth_mid_price     0
wbeth_ask_price     0
wbeth_bid_price     0
wbeth_ask_amount    0
wbeth_bid_amount    0
dtype: int64

In [22]:
btc_wbtc_combined_1m.to_csv('order_book_data/merged_data/1min/btc_wbtc_combined_1m.csv')
eth_wbeth_combined_1m.to_csv('order_book_data/merged_data/1min/eth_wbeth_combined_1m.csv')

In [23]:
# btc_new_data = pd.read_csv('order_book_data/6month_LOB_2024__BTCUSDT.csv')

In [24]:
# btc_new_data